2024-06-18 14:37:44,503 INFO    MainThread:315682 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-06-18 14:37:44,503 INFO    MainThread:315682 [wandb_setup.py:_flush():76] Configure stats pid to 315682
2024-06-18 14:37:44,503 INFO    MainThread:315682 [wandb_setup.py:_flush():76] Loading settings from /mnt/hdd/eric/.config/wandb/settings
2024-06-18 14:37:44,503 INFO    MainThread:315682 [wandb_setup.py:_flush():76] Loading settings from /mnt/hdd/eric/.tmp_ipy/15.Lab_Detection/07.Challenge/01.MapYourCity_HuggingFace/wandb/settings
2024-06-18 14:37:44,503 INFO    MainThread:315682 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-06-18 14:37:44,503 INFO    MainThread:315682 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-06-18 14:37:44,503 INFO    MainThread:315682 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': '07.Challenge/01.MapYourCity_HuggingFace/01.finetune.py', 'program_abspath': '/mnt/hdd/eric/.tmp_ipy/15.Lab_Detection/07.Challenge/01.MapYourCity_HuggingFace/01.finetune.py', 'program': '01.finetune.py'}
2024-06-18 14:37:44,503 INFO    MainThread:315682 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-06-18 14:37:44,503 INFO    MainThread:315682 [wandb_init.py:_log_setup():521] Logging user logs to /mnt/hdd/eric/.tmp_ipy/15.Lab_Detection/07.Challenge/01.MapYourCity_HuggingFace/wandb/run-20240618_143744-26qyrvmu/logs/debug.log
2024-06-18 14:37:44,504 INFO    MainThread:315682 [wandb_init.py:_log_setup():522] Logging internal logs to /mnt/hdd/eric/.tmp_ipy/15.Lab_Detection/07.Challenge/01.MapYourCity_HuggingFace/wandb/run-20240618_143744-26qyrvmu/logs/debug-internal.log
2024-06-18 14:37:44,504 INFO    MainThread:315682 [wandb_init.py:init():561] calling init triggers
2024-06-18 14:37:44,504 INFO    MainThread:315682 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {}
2024-06-18 14:37:44,504 INFO    MainThread:315682 [wandb_init.py:init():611] starting backend
2024-06-18 14:37:44,504 INFO    MainThread:315682 [wandb_init.py:init():615] setting up manager
2024-06-18 14:37:44,507 INFO    MainThread:315682 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-06-18 14:37:44,509 INFO    MainThread:315682 [wandb_init.py:init():623] backend started and connected
2024-06-18 14:37:44,517 INFO    MainThread:315682 [wandb_init.py:init():715] updated telemetry
2024-06-18 14:37:44,584 INFO    MainThread:315682 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-06-18 14:37:45,180 INFO    MainThread:315682 [wandb_run.py:_on_init():2357] communicating current version
2024-06-18 14:37:45,288 INFO    MainThread:315682 [wandb_run.py:_on_init():2366] got version response upgrade_message: "wandb version 0.17.2 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-06-18 14:37:45,289 INFO    MainThread:315682 [wandb_init.py:init():799] starting run threads in backend
2024-06-18 14:37:53,750 WARNING MainThread:315682 [wandb_init.py:init():1203] interrupted
Traceback (most recent call last):
  File "/mnt/hdd/eric/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1181, in init
    run = wi.init()
  File "/mnt/hdd/eric/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 812, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "/mnt/hdd/eric/.local/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/mnt/hdd/eric/.local/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/mnt/hdd/eric/.local/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/mnt/hdd/eric/.conda/envs/mapv2/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/mnt/hdd/eric/.conda/envs/mapv2/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2024-06-18 14:37:58,856 WARNING MsgRouterThr:315682 [router.py:message_loop():77] message_loop has been closed
